name: 'Check Nx Affected'
description: 'Action to check if a nx project has been affected by changes in a branch compared to a base branch.'
author: 'chill-viking'
branding:
  icon: 'help-circle'
  color: 'grey-dark'
inputs:
  project:
    description: 'Name of project to check'
    required: true
  base:
    description: 'Base branch/tag to compare against'
    required: false
    default: 'origin/main'

outputs:
  is-affected:
    description: 'Whether the project specified is affected or not'
  affected-projects:
    description: 'Comma separated list of all affected projects'

runs:
  using: node16
  main: dist/index.js
